name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: cd android &&  chmod +x gradlew

      - name: Build Android
        run: |
          cd android
          ./gradlew assembleDebug


      - name: Upload Android build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload Application
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: android/app/build/outputs/apk/debug/app-debug.apk
